# helmcharts/rancher-helmchart.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/stable
  targetNamespace: cattle-system
  version: 2.7.0
  valuesContent: |-
    hostname: rancher.yourdomain.com
    replicas: 3
