apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarr-rb
  namespace: sonarr
subjects:
- kind: ServiceAccount
  name: radar-sa
  namespace: sonarr
roleRef:
  kind: Role
  name: sonarr-role
  apiGroup: rbac.authorization.k8s.io
