---
# sonarr-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonarr-svc
  namespace: sonarr
spec:
  selector:
    k8s-app: sonarr
  type: NodePort
  ports:
    - name: sonarr
      port: 8989
      targetPort: 8989
      nodePort: 30089
      protocol: TCP