# tautulli-dply.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli-dpl
  namespace: tautulli
  labels:
    k8s-app: tautulli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: tautulli
  template:
    metadata:
      labels:
        k8s-app: tautulli
    spec:
      serviceAccountName: tautulli-sa
      initContainers:
      - name: init-pvc-bound
        image: bitnami/kubectl:latest
        command: ["sh", "/script/init-pvc-bound.sh"]
        volumeMounts:
          - name: script
            mountPath: /script
      containers:
      - name: tautulli
        image: linuxserver/tautulli:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
        env:
        - name: UMASK_SET
          value: "022"
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backup
          mountPath: /backup
        - name: media
          mountPath: /media
        readinessProbe:
          httpGet:
            path: /ping
            port: 7878
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tautulli-pvc
          readOnly: false
      - name: backup
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/backup/tautulli
          readOnly: false
      - name: media
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/media
          readOnly: false
      - name: script
        configMap:
          name: tautulli-cm
          defaultMode: 0755
