---
# tautulli-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: tautulli-svc
  namespace: tautulli
spec:
  selector:
    k8s-app: tautulli
  type: NodePort
  ports:
    - name: tautulli
      port: 8181
      targetPort: 8181
      nodePort: 30081
      protocol: TCP