apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tautulli-rb
  namespace: tautulli
subjects:
- kind: ServiceAccount
  name: tautulli-sa
  namespace: tautulli
roleRef:
  kind: Role
  name: tautulli-role
  apiGroup: rbac.authorization.k8s.io
