---
# tautulli-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: tautulli-svc
  namespace: tautulli
spec:
  selector:
    k8s-app: tautulli
  type: NodePort
  ports:
    - name: tautulli
      port: 8989
      targetPort: 8989
      nodePort: 30089
      protocol: TCP