apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-world
  project: default
  source:
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    chart: hello-world
    helm:
      valuesFiles:
        - ../hello-world/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
