# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nginx-ingress-controller
#   namespace: argocd
# spec:
#   destination: 
#     server: https://kubernetes.default.svc
#     namespace: nginx-ingress-controller
#   project: default
#   sources:
#     - chart: nginx-ingress-controller
#       repoURL: https://charts.bitnami.com/bitnami
#       targetRevision: 11.3.10
#       # helm:
#       #   valueFiles:
#       #   - $values/nginx-ingress-controller/values.yaml
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     automated:
#       selfHeal: true
#       prune: true
