apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nodadyoushutup/kubernetes
    targetRevision: HEAD
    path: nginx-hello-world
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-world

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
