# application/qbittorrent.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent-movie
  namespace: argocd
  labels:
    app: qbittorrent
spec:
  project: default
  source:
    repoURL: https://github.com/nodadyoushutup/kubernetes
    targetRevision: HEAD
    path: qbittorrent/overlays/movie
  destination: 
    server: https://kubernetes.default.svc
    namespace: qbittorrent-movie
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent-television
  namespace: argocd
  labels:
    app: qbittorrent
spec:
  project: default
  source:
    repoURL: https://github.com/nodadyoushutup/kubernetes
    targetRevision: HEAD
    path: qbittorrent/overlays/television
  destination: 
    server: https://kubernetes.default.svc
    namespace: qbittorrent-television
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: qbittorrent-music
#   namespace: argocd
#   labels:
#     app: qbittorrent
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/nodadyoushutup/kubernetes
#     targetRevision: HEAD
#     path: qbittorrent/overlays/music
#   destination: 
#     server: https://kubernetes.default.svc
#     namespace: qbittorrent-music
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     automated:
#       selfHeal: true
#       prune: true
