apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nodadyoushutup/kubernetes
    targetRevision: HEAD
    path: rancher
  destination: 
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
