# qbittorrent/overlays/book.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: qbittorrent-book-sa
roleRef:
  kind: Role
  name: qbittorrent-book-role
  apiGroup: rbac.authorization.k8s.io
