apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: overseerr-rb
  namespace: overseerr
subjects:
- kind: ServiceAccount
  name: overseerr-sa
  namespace: overseerr
roleRef:
  kind: Role
  name: overseerr-role
  apiGroup: rbac.authorization.k8s.io
