---
# overseerr-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: overseerr-svc
  namespace: overseerr
spec:
  selector:
    k8s-app: overseerr
  type: NodePort
  ports:
    - name: overseerr
      port: 5055
      targetPort: 5055
      nodePort: 30055
      protocol: TCP