apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr-cm
  namespace: overseerr
data:
  init-run.sh: |
    #!/bin/sh
    set -e
    export NAMESPACE='overseerr'
    git clone https://github.com/nodadyoushutup/kubernetes.git
    ./kubernetes/script/init.sh
  init-pvc-bound.sh: |
    #!/bin/sh
    echo "Waiting for PVC to be bound..."
    until [ "$(kubectl get pvc overseerr-pvc -n overseerr -o jsonpath='{.status.phase}')" = "Bound" ]; do
      echo "PVC not bound yet. Waiting..."
      sleep 2
    done
    echo "PVC is bound."
  overseerr-volumesnapshot-tarshot.yaml: |
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    metadata:
      name: overseerr-volumesnapshot-tarshot
      namespace: overseerr
    spec:
      volumeSnapshotClassName: rook-cephfs-snapshot-class
      source:
        persistentVolumeClaimName: overseerr-pvc
  overseerr-pvc-tarshot.yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: overseerr-pvc-tarshot
      namespace: overseerr
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      storageClassName: rook-cephfs
      dataSource:
        name: overseerr-volumesnapshot-tarshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
  overseerr-job-tarshot.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: overseerr-job-tarshot
      namespace: overseerr
    spec:
      template:
        spec:
          containers:
          - name: tarcopy
            image: busybox
            command: ["sh", "/script/tarshot-copy.sh"]
            securityContext:
              privileged: true
              runAsUser: 568
              runAsGroup: 568
            volumeMounts:
            - name: pvc
              mountPath: /pvc
            - name: nfs
              mountPath: /nfs
            - name: script
              mountPath: /script
          restartPolicy: OnFailure
          volumes:
          - name: pvc
            persistentVolumeClaim:
              claimName: overseerr-pvc-tarshot
          - name: nfs
            nfs:
              server: 192.168.0.100
              path: /mnt/epool/tarshot/overseerr
              readOnly: false
          - name: script
            configMap:
              name: overseerr-cm
              defaultMode: 0755
  tarshot-run.sh: |
    #!/bin/sh
    set -e
    export NAMESPACE='overseerr'
    git clone https://github.com/nodadyoushutup/kubernetes.git
    ./kubernetes/script/tarshot.sh
  tarshot-copy.sh: |
    #!/bin/sh
    echo "Starting job at $(date)"
    BACKUP_FILE="/nfs/overseerr_backup_$(date +%Y_%m_%d_%H_%M_%S).tar.gz"
    tar -czf ${BACKUP_FILE} /pvc
    chown 568:568 ${BACKUP_FILE}
    echo "Job completed at $(date)"