# qbittorrent/overlays/movie.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: qbittorrent-movie-sa
roleRef:
  kind: Role
  name: qbittorrent-movie-role
  apiGroup: rbac.authorization.k8s.io
