# qbittorrent/overlays/movie/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30125
    # - name: traffic
    #   port: 31125
    #   targetPort: 31125
    #   nodePort: 31125