# qbittorrent/overlays/movie/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent-movie-webui
      port: 8080
      targetPort: 8080
      nodePort: 30125
      protocol: TCP
    - name: qbittorrent-movie-traffic
      port: 31125
      targetPort: 31125
      nodePort: 31125
      protocol: TCP