# qbittorrent/overlays/movie/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  ports:
    - name: qbittorrent
      port: 8080
      targetPort: 8080
      nodePort: 30125
      protocol: TCP
    - name: qbittorrent-traffic
      port: 31125
      targetPort: 31125
      nodePort: 31125
      protocol: TCP