# qbittorrent/overlays/movie/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30125
      protocol: TCP
    - name: traffic
      port: 31025
      targetPort: 31025
      nodePort: 31025
      protocol: TCP