# qbittorrent/overlays/movie/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc-webui
spec:
  type: NodePort
  selector:
    app: qbittorrent
    type: movie
  ports:
    - name: qbittorrent-movie-webui
      port: 8080
      targetPort: 8080
      nodePort: 30125
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-traffic
spec:
  type: NodePort
  selector:
    app: qbittorrent
    type: movie
  ports:
    - name: qbittorrent-movie-traffic
      port: 31125
      targetPort: 31125
      nodePort: 31125
      protocol: TCP
