# readarr-dply.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-dpl
  namespace: readarr
  labels:
    k8s-app: readarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: readarr
  template:
    metadata:
      labels:
        k8s-app: readarr
    spec:
      serviceAccountName: readarr-sa
      initContainers:
      - name: init-pvc-bound
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/init-pvc-bound.sh"]
        volumeMounts:
          - name: script
            mountPath: /script
      - name: init-run
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/init-run.sh"]
        volumeMounts:
          - name: init
            mountPath: /init
          - name: config
            mountPath: /config
          - name: script
            mountPath: /script
        securityContext:
          runAsUser: 0
      containers:
      - name: readarr
        image: linuxserver/readarr:develop
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
        env:
        - name: UMASK_SET
          value: "022"
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backup
          mountPath: /backup
        - name: media
          mountPath: /media
        readinessProbe:
          httpGet:
            path: /ping
            port: 7878
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: readarr-pvc
          readOnly: false
      - name: backup
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/backup/readarr
          readOnly: false
      - name: media
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/media
          readOnly: false
      - name: init
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/init
          readOnly: false
      - name: script
        configMap:
          name: readarr-cm
          defaultMode: 0755
