apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readarr-rb
  namespace: readarr
subjects:
- kind: ServiceAccount
  name: readarr-sa
  namespace: readarr
roleRef:
  kind: Role
  name: readarr-role
  apiGroup: rbac.authorization.k8s.io
