# prowlarr/overlays/television/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: prowlarr-television-sa
      initContainers:
      - name: pvc-bound
        envFrom:
          - configMapRef:
              name: prowlarr-television-cm
      - name: init-run
        envFrom:
          - configMapRef:
              name: prowlarr-television-cm
      containers:
      - name: prowlarr
        envFrom:
          - configMapRef:
              name: prowlarr-television-cm
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-television-pvc
      - name: script
        configMap:
          name: prowlarr-television-cm