# qbittorrent/overlays/television.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: qbittorrent-television-sa
roleRef:
  kind: Role
  name: qbittorrent-television-role
  apiGroup: rbac.authorization.k8s.io
