# qbittorrent/overlays/television/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  ports:
    - name: qbittorrent
      port: 8080
      targetPort: 8080
      nodePort: 30225
      protocol: TCP