# qbittorrent/overlays/television/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: qbittorrent-television
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent
      port: 8080
      targetPort: 8080
      nodePort: 30225
      protocol: TCP
    - name: qbittorrent-traffic
      port: 31225
      targetPort: 31225
      nodePort: 31225
      protocol: TCP
