---
# backup/job-tarshot.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ${NAMESPACE}-job-tarshot
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: tarcopy
        image: bitnami/kubectl:latest
        command: ["sh", "/script/tarshot-copy.sh"]
        securityContext:
          privileged: true
          runAsUser: 568
          runAsGroup: 568
        env:
          - name: NAMESPACE
            value: ${NAMESPACE}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tarshot
          mountPath: /tarshot
        - name: script
          mountPath: /script
        - name: git
          mountPath: /git
      restartPolicy: OnFailure
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: ${NAMESPACE}-pvc-tarshot
      - name: tarshot
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/tarshot/${NAMESPACE}
          readOnly: false
      - name: script
        configMap:
          name: ${NAMESPACE}-cm
          defaultMode: 0755
      - name: git
        emptyDir: {}