apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NAMESPACE}-pvc-tarshot
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
  dataSource:
    name: ${NAMESPACE}-volumesnapshot-tarshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io