---
# script/volumesnapshot-tarshot.yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ${NAMESPACE}-volumesnapshot-tarshot
  namespace: ${NAMESPACE}
spec:
  volumeSnapshotClassName: rook-cephfs-snapshot-class
  source:
    persistentVolumeClaimName: ${NAMESPACE}-pvc