apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nodadyoushutup/kubernetes
    targetRevision: HEAD
    path: radarr
  destination: 
    server: https://kubernetes.default.svc
    namespace: radarr
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
