---
apiVersion: v1
kind: Pod
metadata:
  name: radarr-debug
  labels:
    k8s-app: radarr-debug
spec:
  containers:
  - name: debug
    image: ubuntu:20.04
    imagePullPolicy: IfNotPresent
    command: [ "sh", "-c", "sleep 360000" ] # Keeps the container running
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: radarr-pvc
  restartPolicy: Never