# radarr-dply.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-deploy
  namespace: radarr
  labels:
    k8s-app: radarr
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: radarr
  template:
    metadata:
      labels:
        k8s-app: radarr
    spec:
      serviceAccountName: radarr-sa
      initContainers:
      - name: init
        image: ghcr.io/nodadyoushutup/init:0.0.14
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/radarr.sh"]
        volumeMounts:
          - name: config
            mountPath: /app
        securityContext:
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: radarr-cm
      containers:
      - name: radarr
        image: linuxserver/radarr:5.7.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
        envFrom:
        - configMapRef:
            name: radarr-cm
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backup
          mountPath: /backup
        - name: media
          mountPath: /media
        readinessProbe:
          httpGet:
            path: /ping
            port: 7878
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-pvc
          readOnly: false
      - name: backup
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/backup/radarr
          readOnly: false
      - name: media
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/media
          readOnly: false