apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: radarr-rb-snapshot
  namespace: radarr
subjects:
- kind: ServiceAccount
  name: radar-sa-snapshot
  namespace: radarr
roleRef:
  kind: Role
  name: radarr-role-snapshot
  apiGroup: rbac.authorization.k8s.io
