# radarr-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: radarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: radarr-config-snapshot-pvc
#   namespace: radarr
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: rook-cephfs
#   dataSource:
#     name: radarr-config-snapshot
#     kind: VolumeSnapshot
#     apiGroup: snapshot.storage.k8s.io
