apiVersion: v1
kind: Service
metadata:
  name: radarr-svc
  namespace: radarr
  annotations:
    metallb.universe.tf/address: 192.168.0.200
spec:
  selector:
    k8s-app: radarr
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
  type: LoadBalancer
