apiVersion: batch/v1
kind: Job
metadata:
  name: radarr-tarcopy-job
  namespace: radarr
spec:
  template:
    spec:
      initContainers:
      - name: check-radarr-dpl
        image: bitnami/kubectl:latest
        command: ["sh", "-c", "kubectl rollout status deployment/radarr-dpl -n radarr"]
        volumeMounts:
        - name: pvc
          mountPath: /pvc
        env:
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
      containers:
      - name: tarcopy
        image: busybox
        command: ["sh", "/scripts/tarcopy.sh"]
        securityContext:
          runAsUser: 568
        volumeMounts:
        - name: pvc
          mountPath: /pvc
        - name: nfs
          mountPath: /nfs
        - name: script
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: radarr-config-snapshot-pvc
      - name: nfs
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/tarshots/radarr
      - name: script
        configMap:
          name: radarr-cm-tarcopy
          defaultMode: 0755
