# radarr-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-config
  namespace: radarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs