apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-cm-tarcopy
  namespace: radarr
data:
  tarcopy.sh: |
    #!/bin/sh
    echo "Starting job at $(date)"
    cd /pvc
    tar -czf /nfs/radarr_backup_$(date +%Y_%m_%d_%H_%M_%S).tar.gz .
    echo "Job completed at $(date)"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-cm-tarcopy
  namespace: radarr
data:
  tarcopy.sh: |
    #!/bin/sh
    echo "Starting job at $(date)"
    cd /pvc
    tar -czf /nfs/radarr_backup_$(date +%Y_%m_%d_%H_%M_%S).tar.gz .
    echo "Job completed at $(date)"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-snapshot-script
  namespace: radarr
data:
  radarr-volumesnapshot.yaml: |
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    metadata:
      name: radarr-config-snapshot
      namespace: radarr
    spec:
      volumeSnapshotClassName: rook-cephfs-snapshot-class
      source:
        persistentVolumeClaimName: radarr-config-pvc
  radarr-pvc.yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: radarr-config-snapshot-pvc
      namespace: radarr
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: rook-cephfs
      dataSource:
        name: radarr-config-snapshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
  radarr-job.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: radarr-tarcopy-job
      namespace: radarr
    spec:
      template:
        spec:
          containers:
          - name: tarcopy
            image: busybox
            command: ["sh", "/scripts/tarcopy.sh"]
            securityContext:
              runAsUser: 568
              runAsGroup: 568
            volumeMounts:
            - name: pvc
              mountPath: /pvc
            - name: nfs
              mountPath: /nfs
            - name: script
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: pvc
            persistentVolumeClaim:
              claimName: radarr-config-snapshot-pvc
          - name: nfs
            nfs:
              server: 192.168.0.100
              path: /mnt/epool/tarshots/radarr
          - name: script
            configMap:
              name: radarr-cm-tarcopy
              defaultMode: 0755
  snapshot-script.sh: |
    #!/bin/sh
    set -e

    log() {
      echo "$(date +'%Y-%m-%d %H:%M:%S') - $1"
    }

    log "Starting backup job..."

    # Step 1: Create new assets
    ### VolumeSnapshot ###
    kubectl log "Applying VolumeSnapshot configuration" && apply -f /scripts/radarr-volumesnapshot.yaml
    while [ "$(kubectl get volumesnapshot radarr-config-snapshot -n radarr -o jsonpath='{.status.readyToUse}')" != "true" ]; do
      log "Waiting for the VolumeSnapshot to be ready..."
      sleep 10
    done

    ### PVC ###
    log "Applying PVC configuration" && kubectl apply -f /scripts/radarr-pvc.yaml
    while [ "$(kubectl get pvc radarr-config-snapshot-pvc -n radarr -o jsonpath='{.status.phase}')" != "Bound" ]; do
      log "Waiting for the PVC to be bound..."
      sleep 10
    done

    ### JOB ###
    log "Applying Job configuration" && kubectl apply -f /scripts/radarr-job.yaml 
    while [ "$(kubectl get job radarr-tarcopy-job -n radarr -o jsonpath='{.status.succeeded}')" != "1" ]; do
      log "Waiting for the Job to complete..."
      sleep 10
    done

    log "Backup job completed"

    # Step 2: Delete existing assets
    log "Removing finalizers from VolumeSnapshot"
    kubectl patch volumesnapshot radarr-config-snapshot -n radarr --type=json -p '[{"op": "remove", "path": "/metadata/finalizers"}]' && log "Finalizers removed from VolumeSnapshot"
    log "Removing finalizers from PVC"
    kubectl patch pvc radarr-config-snapshot-pvc -n radarr --type=json -p '[{"op": "remove", "path": "/metadata/finalizers"}]' && log "Finalizers removed from PVC"
    log "Deleting Job"
    kubectl delete job radarr-tarcopy-job -n radarr --ignore-not-found && log "Job deleted"
    log "Deleting VolumeSnapshot"
    kubectl delete volumesnapshot radarr-config-snapshot -n radarr --ignore-not-found && log "VolumeSnapshot deleted"
    log "Deleting PVC"
    kubectl delete pvc radarr-config-snapshot-pvc -n radarr --ignore-not-found && log "PVC deleted"

    log "Assets cleaned up"