apiVersion: batch/v1
kind: Job
metadata:
  name: tarcopy
  namespace: radarr
spec:
  template:
    spec:
      initContainers:
      - name: chown-nfs
        image: busybox
        command: ["sh", "-c", "chown -R 568:568 /nfs"]
        volumeMounts:
        - name: nfs
          mountPath: /nfs
      containers:
      - name: tarcopy
        image: busybox
        command: ["sh", "-c", "cd /pvc && tar -czf /nfs/radarr-backup-$(date +%Y%m%d%H%M%S).tar.gz ."]
        volumeMounts:
        - name: pvc
          mountPath: /pvc
        - name: nfs
          mountPath: /nfs
      restartPolicy: OnFailure
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: radarr-config-pvc
      - name: nfs
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/tarshots/radarr
