apiVersion: batch/v1
kind: CronJob
metadata:
  name: tarcopy-cron
  namespace: radarr
spec:
  schedule: "*/5 * * * *" # This schedule runs the job every 5 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tarcopy
            image: busybox
            command: ["sh", "/scripts/tarcopy.sh"]
            securityContext:
              runAsUser: 568
            volumeMounts:
            - name: pvc
              mountPath: /pvc
            - name: nfs
              mountPath: /nfs
            - name: script
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: pvc
            persistentVolumeClaim:
              claimName: radarr-config-pvc
          - name: nfs
            nfs:
              server: 192.168.0.100
              path: /mnt/epool/tarshots/radarr
          - name: script
            configMap:
              name: tarcopy-script
              defaultMode: 0755
