---
# prowlarr/base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-cm
data:
  pvc-bound.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /git
    ./git/script/pvc-bound.sh
  tarshot.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /git
    ./git/script/tarshot.sh