---
# prowlarr/base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  pvc-bound.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /git
    ./git/script/pvc-bound.sh
  tarshot.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /git
    ./git/script/tarshot.sh
  volumesnapshot-tarshot.yaml: |
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    metadata:
      name: ${NAMESPACE}-volumesnapshot-tarshot
      namespace: ${NAMESPACE}
    spec:
      volumeSnapshotClassName: rook-cephfs-snapshot-class
      source:
        persistentVolumeClaimName: ${NAMESPACE}-pvc