apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  appname: prowlarr
  init-pvc-bound.sh: |
    #!/bin/sh
    echo "Waiting for PVC to be bound..."
    until [ "$(kubectl get pvc ${appname} -n prowlarr -o jsonpath='{.status.phase}')" = "Bound" ]; do
      echo "PVC not bound yet. Waiting..."
      sleep 2
    done
    echo "PVC is bound."
