---
# prowlarr/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    k8s-app: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        k8s-app: prowlarr
    spec:
      serviceAccountName: prowlarr-sa
      initContainers:
      - name: pvc-bound
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/pvc-bound.sh"]
        volumeMounts:
          - name: script
            mountPath: /script
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9696
        env:
        - name: UMASK_SET
          value: "022"
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
        volumeMounts:
        - name: config
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /status
            port: 9696
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: script
        configMap:
          name: prowlarr-base-cm
          defaultMode: 0755
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-pvc
          readOnly: false
