---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-deploy
  namespace: prowlarr
  labels:
    k8s-app: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: prowlarr
  template:
    metadata:
      labels:
        k8s-app: prowlarr
    spec:
      serviceAccountName: prowlarr-sa
      # initContainers:
      # - name: init-pvc-bound
      #   image: bitnami/kubectl:latest
      #   imagePullPolicy: IfNotPresent
      #   command: ["sh", "/script/init-pvc-bound.sh"]
      #   volumeMounts:
      #     - name: script
      #       mountPath: /script
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9696
        env:
        - name: UMASK_SET
          value: "022"
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
        volumeMounts:
        - name: config
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /status
            port: 9696
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-pvc
          readOnly: false
      - name: init
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/init
          readOnly: false
      - name: script
        configMap:
          name: prowlarr-cm
          defaultMode: 0755
