---
# prowlarr/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    k8s-app: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    spec:
      serviceAccountName: prowlarr-sa
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9696
        env:
        - name: UMASK_SET
          value: "022"
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
        volumeMounts:
        - name: config
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /status
            port: 9696
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-pvc
          readOnly: false
