# prowlarr/base/kustomization.yaml
resources:
  - persistentvolumeclaim.yaml
  - namespace.yaml

commonLabels:
  app: prowlarr

commonAnnotations:
  app: prowlarr-annontations

namePrefix:
  prowlarr-
