# prowlarr/base/kustomization.yaml
resources:
  - persistentvolumeclaim.yaml
  - role.yaml
  - service.yaml
  - deployment.yaml
  - cronjob.yaml
  - configmap.yaml

commonLabels:
  app: prowlarr

commonAnnotations:
  app: prowlarr-annontations