# prowlarr/base/kustomization.yaml
resources:
  - persistentvolumeclaim.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml

commonLabels:
  app: prowlarr

commonAnnotations:
  app: prowlarr-annontations

# namePrefix:
#   prowlarr-
