# prowlarr/base/kustomization.yaml
resources:
  - configmap.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  # - persistentvolumeclaim.yaml
  # - service.yaml
  # - deployment.yaml
  # - cronjob.yaml

namespace: prowlarr

commonLabels:
  app: prowlarr

commonAnnotations:
  app: prowlarr-annontations