# prowlarr/base/kustomization.yaml
resources:
  - persistentvolumeclaim.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
  - deployment.yaml

commonLabels:
  app: prowlarr

commonAnnotations:
  app: prowlarr-annontations