# prowlarr/base/rolebinding.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: prowlarr-sa
roleRef:
  kind: Role
  name: prowlarr-role
  apiGroup: rbac.authorization.k8s.io
