# qbittorrent/base/configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  pvc-bound.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /tmp/git
    ./tmp/git/script/pvc-bound.sh
  tarshot.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /tmp/git
    ./tmp/git/script/tarshot.sh
  tarshot-copy.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /tmp/git
    ./tmp/git/script/tarshot-copy.sh
  qbittorrent-config.sh: |
    #!/bin/sh
    set -e
    git clone https://github.com/nodadyoushutup/kubernetes.git /tmp/git
    ./tmp/git/script/qbittorrent-config.sh
  qBittorrent-default.conf: |
    [AutoRun]
    enabled=false
    program=

    [LegalNotice]
    Accepted=true

    [Preferences]
    Connection\UPnP=false
    Connection\PortRangeMin=6881
    Downloads\SavePath=/downloads/
    Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
    Downloads\TempPath=/downloads/incomplete/
    WebUI\Address=*
    WebUI\ServerDomains=*
    WebUI\HostHeaderValidation=false
    WebUI\Username=admin
    WebUI\Password_PBKDF2="@ByteArray(2not9r6jLIKcHuU/4MkA9g==:2XUrgHJMZ9A2eQR2SvnASD/15W2JoQ/YtkaRzOgTQRFIVLCcJELC6Y19Jv2rXSDQSN/MKKV/JtWzi2dNPRFeVw==)"