---
apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent-debug
  labels:
    k8s-app: qbittorrent-debug
spec:
  containers:
  - name: debug
    image: ubuntu:24.04
    imagePullPolicy: IfNotPresent
    command: [ "sh", "-c", "sleep 360000" ] # Keeps the container running
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: qbittorrent-movie-pvc
  restartPolicy: Never