# qbittorrent/base/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: qbittorrent
    type: qbittorrent
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
        type: qbittorrent
    spec:
      serviceAccountName: qbittorrent-sa
      initContainers:
      - name: pvc-bound
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/pvc-bound.sh"]
        volumeMounts:
          - name: script
            mountPath: /script
        envFrom:
          - configMapRef:
              name: qbittorrent-movie-cm
      - name: set-config
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/qbittorrent-config.sh"]
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - name: script
            mountPath: /script
          - name: config
            mountPath: /config
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 31125
          protocol: TCP
        - containerPort: 31125
          protocol: UDP
        envFrom:
          - configMapRef:
              name: qbittorrent-cm
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: torrents
          mountPath: /torrents
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: script
        configMap:
          name: qbittorrent-cm
          defaultMode: 0755
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-pvc
      - name: media
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/media
      - name: torrents
        nfs:
          server: 192.168.0.100
          path: /mnt/epool/config/torrents
