# qbittorrent/base/kustomization.yaml
---
resources:
  - configmap.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  # - cronjob.yaml
  # - debug.yaml

namespace: qbittorrent
commonLabels:
  app: qbittorrent

commonAnnotations:
  app: qbittorrent-annontations