# qbittorrent/base/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent
      port: 8080
      targetPort: 8080
      nodePort: 30125
      protocol: TCP