kubePlex:
  mounts: /data,/transcode
persistence:
  config:
    claimName: kube-plex-pvc-config
    storageClass: rook-cephfs
  data:
    claimName: kube-plex-pvc-data
    storageClass: rook-cephfs
  transcode:
    storageClass: rook-cephfs
    enabled: true
    claimName: kube-plex-pvc-transcode
    size: 50Gi
    accessMode: ReadWriteMany
# service:
#   loadBalancerIP: 192.168.0.200
# externalTrafficPolicy: Local 
ingres:
  enabled: true