apiVersion: v1
kind: Service
metadata:
  name: argocd-svc-dashboard
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
