apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-role
  namespace: kube-plex
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-role-binding
  namespace: kube-plex
subjects:
- kind: ServiceAccount
  name: kube-plex-kube-plex
  namespace: kube-plex
roleRef:
  kind: Role
  name: exec-role
  apiGroup: rbac.authorization.k8s.io