# qbittorrent/overlays/music.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: qbittorrent-music-sa
roleRef:
  kind: Role
  name: qbittorrent-music-role
  apiGroup: rbac.authorization.k8s.io
