# qbittorrent/overlays/music/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc-webui
spec:
  type: NodePort
  selector:
    app: qbittorrent
    type: music
  ports:
    - name: qbittorrent-music-webui
      port: 8080
      targetPort: 8080
      nodePort: 30325
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-traffic
spec:
  type: NodePort
  selector:
    app: qbittorrent
    type: music
  ports:
    - name: qbittorrent-music-traffic
      port: 31325
      targetPort: 31325
      nodePort: 31325
      protocol: TCP
