# qbittorrent/overlays/music/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30325
      protocol: TCP
    - name: traffic
      port: 31325
      targetPort: 31325
      nodePort: 31325
      protocol: TCP