# qbittorrent/overlays/cross-seed.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: qbittorrent-cross-seed-sa
roleRef:
  kind: Role
  name: qbittorrent-cross-seed-role
  apiGroup: rbac.authorization.k8s.io
