---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: prowlarr-movie
spec:
  template:
    spec:
      serviceAccountName: prowlarr-movie-sa
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-movie-pvc
