# prowlarr/overlays/movie/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: prowlarr-movie-sa
      initContainers:
      - name: pvc-bound
        envFrom:
          - configMapRef:
              name: prowlarr-movie-cm
      containers:
      - name: prowlarr
        envFrom:
          - configMapRef:
              name: prowlarr-cm
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-movie-pvc
      - name: script
        configMap:
          name: prowlarr-movie-cm