---
# prowlarr/overlays/movie/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: prowlarr-movie-sa
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-movie-pvc
      - name: script
        configMap:
          name: prowlarr-movie-base-cm