# prowlarr/overlays/movie/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: prowlarr-movie-sa
      initContainers:
      - name: pvc-bound
        envFrom:
          - configMapRef:
              name: prowlarr-movie-cm
      - name: init-run
        image: ghcr.io/nodadyoushutup/init:0.0.6
        imagePullPolicy: IfNotPresent
        command: ["sh", "/script/prowlarr-movie.sh"]
        volumeMounts:
          - name: config
            mountPath: /app
        securityContext:
          runAsUser: 0
      containers:
      - name: prowlarr
        envFrom:
          - configMapRef:
              name: prowlarr-movie-cm
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-movie-pvc
      - name: script
        configMap:
          name: prowlarr-movie-cm