apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  

namespace: prowlarr-movie

patches:
- namespace.yaml

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties