apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prowlarr-movie

patches:
  - path: namespace.yaml

# Uncomment and customize the following if needed
# configMapGenerator:
# - name: mykustom-map
#   env: config.properties
