apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: prowlarr-movie-cm
    files:
      - prowlarr-movie-cm.yaml

patches:
  - target:
      kind: ConfigMap
      name: prowlarr-movie-cm
    path: prowlarr-movie-cm.yaml
  - path: prowlarr-movie-cronjob.yaml
  - path: prowlarr-movie-deploy.yaml
  - path: prowlarr-movie-ns.yaml
  - path: prowlarr-movie-pvc.yaml
  - path: prowlarr-movie-rb.yaml
  - path: prowlarr-movie-role.yaml
  - path: prowlarr-movie-sa.yaml
  - path: prowlarr-movie-svc.yaml
