---
# prowlarr/overlays/movie/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prowlarr-movie

namePrefix:
  prowlarr-movie-

patches:
  - path: rolebinding.yaml
  # - path: service.yaml
  # - path: deployment.yaml
  
  

configMapGenerator:
  - name: cm
    behavior: merge
    # literals:
    #   - additional-config-key=additional-config-value
    env: config.properties