---
# prowlarr/overlays/movie/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prowlarr-movie

namePrefix:
  prowlarr-movie-

patches:
  - path: deployment.yaml