apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: prowlarr-movie

# patches:
# - replicas.yaml

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties