---
# prowlarr/prowlarr-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-movie-cm
  namespace: prowlarr-movie
data:
  init-run.sh: |
    #!/bin/sh
    set -e
    export NAMESPACE='prowlarr'
    git clone https://github.com/nodadyoushutup/kubernetes.git
    ./kubernetes/script/init.sh
  init-pvc-bound.sh: |
    #!/bin/sh
    echo "Waiting for PVC to be bound..."
    until [ "$(kubectl get pvc prowlarr-pvc -n prowlarr -o jsonpath='{.status.phase}')" = "Bound" ]; do
      echo "PVC not bound yet. Waiting..."
      sleep 2
    done
    echo "PVC is bound."
  prowlarr-volumesnapshot-tarshot.yaml: |
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    metadata:
      name: prowlarr-volumesnapshot-tarshot
      namespace: prowlarr
    spec:
      volumeSnapshotClassName: rook-cephfs-snapshot-class
      source:
        persistentVolumeClaimName: prowlarr-pvc
  prowlarr-pvc-tarshot.yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: prowlarr-pvc-tarshot
      namespace: prowlarr
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      storageClassName: rook-cephfs
      dataSource:
        name: prowlarr-volumesnapshot-tarshot
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
  prowlarr-job-tarshot.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: prowlarr-job-tarshot
      namespace: prowlarr
    spec:
      template:
        spec:
          containers:
          - name: tarcopy
            image: busybox
            command: ["sh", "/script/tarshot-copy.sh"]
            securityContext:
              privileged: true
              runAsUser: 568
              runAsGroup: 568
            volumeMounts:
            - name: pvc
              mountPath: /pvc
            - name: nfs
              mountPath: /nfs
            - name: script
              mountPath: /script
          restartPolicy: OnFailure
          volumes:
          - name: pvc
            persistentVolumeClaim:
              claimName: prowlarr-pvc-tarshot
          - name: nfs
            nfs:
              server: 192.168.0.100
              path: /mnt/epool/tarshot/prowlarr
              readOnly: false
          - name: script
            configMap:
              name: prowlarr-cm
              defaultMode: 0755
  tarshot-run.sh: |
    #!/bin/sh
    set -e
    export NAMESPACE='prowlarr'
    git clone https://github.com/nodadyoushutup/kubernetes.git
    ./kubernetes/script/tarshot.sh
  tarshot-copy.sh: |
    #!/bin/sh
    echo "Starting job at $(date)"
    BACKUP_FILE="/nfs/prowlarr_backup_$(date +%Y_%m_%d_%H_%M_%S).tar.gz"
    tar -czf ${BACKUP_FILE} /pvc
    chown 568:568 ${BACKUP_FILE}
    echo "Job completed at $(date)"