apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-cm
  namespace: prowlarr
data:
  init-run.sh: |
    #!/bin/sh
    set -e
    export NAMESPACE='prowlarr'
    git clone https://github.com/nodadyoushutup/kubernetes.git
    ./kubernetes/script/init_movies.sh
  init-pvc-bound.sh: |
    #!/bin/sh
    echo "Waiting for PVC to be bound..."
    until [ "$(kubectl get pvc prowlarr-pvc -n prowlarr -o jsonpath='{.status.phase}')" = "Bound" ]; do
      echo "PVC not bound yet. Waiting..."
      sleep 2
    done
    echo "PVC is bound."
  tarshot-run.sh: |
    #!/bin/sh
    set -e
    export NAMESPACE='prowlarr'
    git clone https://github.com/nodadyoushutup/kubernetes.git
    ./kubernetes/script/tarshot_movies.sh
  tarshot-copy.sh: |
    #!/bin/sh
    echo "Starting job at $(date)"
    BACKUP_FILE="/nfs/prowlarr_backup_movies_$(date +%Y_%m_%d_%H_%M_%S).tar.gz"
    tar -czf ${BACKUP_FILE} /pvc
    chown 568:568 ${BACKUP_FILE}
    echo "Job completed at $(date)"
