---
# prowlarr/overlays/movie.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: prowlarr-movie-sa
roleRef:
  kind: Role
  name: prowlarr-movie-role
  apiGroup: rbac.authorization.k8s.io
