apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@nodadyoushutup.com # Replace with your email address
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: jacobfholland@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
