# prowlarr/prowlarr-cronjob.yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-tarshot
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: prowlarr-music-sa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          containers:
          - name: tarshot
            envFrom:
              - configMapRef:
                  name: prowlarr-music-cm
          volumes:
          - name: script
            configMap:
              name: prowlarr-music-cm
              defaultMode: 0755
          - name: config
            persistentVolumeClaim:
              claimName: prowlarr-music-pvc
              readOnly: false
          - name: backup
            nfs:
              path: /mnt/epool/backup/prowlarr-music
