# prowlarr/overlays/music.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
subjects:
- kind: ServiceAccount
  name: prowlarr-music-sa
roleRef:
  kind: Role
  name: prowlarr-music-role
  apiGroup: rbac.authorization.k8s.io
