# prowlarr/overlays/musics/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  ports:
    - name: prowlarr
      port: 9696
      targetPort: 9696
      nodePort: 30196
      protocol: TCP