---
apiVersion: v1
kind: Pod
metadata:
  name: jellyseerr-debug
  labels:
    k8s-app: jellyseerr-debug
spec:
  containers:
  - name: debug
    image: ubuntu:24.04
    imagePullPolicy: IfNotPresent
    command: [ "sh", "-c", "sleep 360000" ] # Keeps the container running
    volumeMounts:
    - name: app
      mountPath: /app
    - name: media
      mountPath: /media
  volumes:
  - name: app
    persistentVolumeClaim:
      claimName: jellyseerr-pvc
  - name: media
    nfs:
      server: 192.168.0.100
      path: /mnt/epool/media
      readOnly: false
  restartPolicy: Never