# jellyseerr-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-pvc
  namespace: jellyseerr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs