---
# jellyseerr-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr-svc
  namespace: jellyseerr
spec:
  selector:
    k8s-app: jellyseerr
  type: NodePort
  ports:
    - name: jellyseerr
      port: 5055
      targetPort: 5055
      nodePort: 30055
      protocol: TCP